///
/// HybridCalendarSpec.swift
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © 2025 Marc Rousavy @ Margelo
///

import Foundation
import NitroModules

/// See ``HybridCalendarSpec``
public protocol HybridCalendarSpec_protocol: HybridObject, HybridView {
  // Properties
  var colorScheme: ColorScheme { get set }
  var isBlue: Bool { get set }
  var someCallback: () -> Void { get set }

  // Methods
  func someMethod() throws -> Void
}

/// See ``HybridCalendarSpec``
public class HybridCalendarSpec_base {
  private weak var cxxWrapper: HybridCalendarSpec_cxx? = nil
  public func getCxxWrapper() -> HybridCalendarSpec_cxx {
  #if DEBUG
    guard self is HybridCalendarSpec else {
      fatalError("`self` is not a `HybridCalendarSpec`! Did you accidentally inherit from `HybridCalendarSpec_base` instead of `HybridCalendarSpec`?")
    }
  #endif
    if let cxxWrapper = self.cxxWrapper {
      return cxxWrapper
    } else {
      let cxxWrapper = HybridCalendarSpec_cxx(self as! HybridCalendarSpec)
      self.cxxWrapper = cxxWrapper
      return cxxWrapper
    }
  }
}

/**
 * A Swift base-protocol representing the Calendar HybridObject.
 * Implement this protocol to create Swift-based instances of Calendar.
 * ```swift
 * class HybridCalendar : HybridCalendarSpec {
 *   // ...
 * }
 * ```
 */
public typealias HybridCalendarSpec = HybridCalendarSpec_protocol & HybridCalendarSpec_base
