///
/// NitroCalendar-Swift-Cxx-Bridge.cpp
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © 2025 Marc Rousavy @ Margelo
///

#include "NitroCalendar-Swift-Cxx-Bridge.hpp"

// Include C++ implementation defined types
#include "HybridCalendarSpecSwift.hpp"
#include "NitroCalendar-Swift-Cxx-Umbrella.hpp"

namespace margelo::nitro::calendar::bridge::swift {

  // pragma MARK: std::function<void()>
  Func_void create_Func_void(void* _Nonnull swiftClosureWrapper) {
    auto swiftClosure = NitroCalendar::Func_void::fromUnsafe(swiftClosureWrapper);
    return [swiftClosure = std::move(swiftClosure)]() mutable -> void {
      swiftClosure.call();
    };
  }
  
  // pragma MARK: std::shared_ptr<margelo::nitro::calendar::HybridCalendarSpec>
  std::shared_ptr<margelo::nitro::calendar::HybridCalendarSpec> create_std__shared_ptr_margelo__nitro__calendar__HybridCalendarSpec_(void* _Nonnull swiftUnsafePointer) {
    NitroCalendar::HybridCalendarSpec_cxx swiftPart = NitroCalendar::HybridCalendarSpec_cxx::fromUnsafe(swiftUnsafePointer);
    return std::make_shared<margelo::nitro::calendar::HybridCalendarSpecSwift>(swiftPart);
  }
  void* _Nonnull get_std__shared_ptr_margelo__nitro__calendar__HybridCalendarSpec_(std__shared_ptr_margelo__nitro__calendar__HybridCalendarSpec_ cppType) {
    std::shared_ptr<margelo::nitro::calendar::HybridCalendarSpecSwift> swiftWrapper = std::dynamic_pointer_cast<margelo::nitro::calendar::HybridCalendarSpecSwift>(cppType);
  #ifdef NITRO_DEBUG
    if (swiftWrapper == nullptr) [[unlikely]] {
      throw std::runtime_error("Class \"HybridCalendarSpec\" is not implemented in Swift!");
    }
  #endif
    NitroCalendar::HybridCalendarSpec_cxx& swiftPart = swiftWrapper->getSwiftPart();
    return swiftPart.toUnsafe();
  }

} // namespace margelo::nitro::calendar::bridge::swift
