///
/// NitroCalendarAutolinking.mm
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © 2025 Marc Rousavy @ Margelo
///

#import <Foundation/Foundation.h>
#import <NitroModules/HybridObjectRegistry.hpp>
#import "NitroCalendar-Swift-Cxx-Umbrella.hpp"
#import <type_traits>

#include "HybridCalendarSpecSwift.hpp"

@interface NitroCalendarAutolinking : NSObject
@end

@implementation NitroCalendarAutolinking

+ (void) load {
  using namespace margelo::nitro;
  using namespace margelo::nitro::calendar;

  HybridObjectRegistry::registerHybridObjectConstructor(
    "Calendar",
    []() -> std::shared_ptr<HybridObject> {
      std::shared_ptr<margelo::nitro::calendar::HybridCalendarSpec> hybridObject = NitroCalendar::NitroCalendarAutolinking::createCalendar();
      return hybridObject;
    }
  );
}

@end
