///
/// NitroCalendarAutolinking.swift
/// This file was generated by nitrogen. DO NOT MODIFY THIS FILE.
/// https://github.com/mrousavy/nitro
/// Copyright © 2025 Marc Rousavy @ Margelo
///

public final class NitroCalendarAutolinking {
  public typealias bridge = margelo.nitro.calendar.bridge.swift

  /**
   * Creates an instance of a Swift class that implements `HybridCalendarSpec`,
   * and wraps it in a Swift class that can directly interop with C++ (`HybridCalendarSpec_cxx`)
   *
   * This is generated by Nitrogen and will initialize the class specified
   * in the `"autolinking"` property of `nitro.json` (in this case, `HybridCalendar`).
   */
  public static func createCalendar() -> bridge.std__shared_ptr_margelo__nitro__calendar__HybridCalendarSpec_ {
    let hybridObject = HybridCalendar()
    return { () -> bridge.std__shared_ptr_margelo__nitro__calendar__HybridCalendarSpec_ in
      let __cxxWrapped = hybridObject.getCxxWrapper()
      return __cxxWrapped.getCxxPart()
    }()
  }
}
